// <autogenerated>
//   This file was generated by T4 code generator Configuration.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

//=============================================================================
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//=============================================================================
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
namespace IDal
{
    public interface IBaseDal<T> where T : class,new()
    {
        IQueryable<T> GetList(Expression<Func<T, bool>> whereLambda);
        IQueryable<T> GetPagingList<S>(int pageIndex, int pageSize, out int totalCount, bool isDec, Expression<Func<T, bool>> whereLambda, Expression<Func<T, S>> orderByLambda);
        T Add(T model);
        IEnumerable<T> AddRange(IEnumerable<T> models);
        int GetUpdate(Expression<Func<T, bool>> whereLambda, Expression<Func<T, T>> updateLambda);
        int Update(T model);
        bool UpdateEntityList(IEnumerable<T> entityList);
        int DeleteReal(Expression<Func<T, bool>> whereLambda);
        int DeleteFake(Expression<Func<T, bool>> whereLambda, Expression<Func<T, T>> updateLambda);
    }
}
