// <autogenerated>
//   This file was generated by T4 code generator Configuration.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

//=============================================================================
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//=============================================================================
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using IDal;
namespace IDal
{
    public interface IDbSession
    {
        DbContext entity { get; }
        IAuthorityDal AuthorityDal { get; set; }
        IFileDal FileDal { get; set; }
        IGoodsDal GoodsDal { get; set; }
        IOrganizeDal OrganizeDal { get; set; }
        IRoleDal RoleDal { get; set; }
        ITypeDal TypeDal { get; set; }
        IUserDal UserDal { get; set; }
        ITagDal TagDal { get; set; }
        IUserUpFileDal UserUpFileDal { get; set; }
        IUserDataDal UserDataDal { get; set; }
        ILevelDal LevelDal { get; set; }
        int ExcuteSql(string sql, object[] parameters);
        bool SaveChanges();
    }
}
